import dataclasses
import dataclasses_json


@dataclasses_json.dataclass_json
@dataclasses.dataclass
class LanguageLang:
    lang_1000_mews: str
    lang_1000_mole_cash: str
    lang_1000_xp: str
    lang_100_festival_tokens: str
    lang_100_task_tokens: str
    lang_accept_task: str
    lang_accessibility: str
    lang_accessibility_options_dialog: str
    lang_accessibility_title: str
    lang_accessibility_tooltip: str
    lang_accessories: str
    lang_accessories_title: str
    lang_accessory: str
    lang_accessory_tip: str
    lang_achievement_description_abundance: str
    lang_achievement_description_accent_piece: str
    lang_achievement_description_adept_of_the_abyss: str
    lang_achievement_description_archaeologist_of_ancient_treasure: str
    lang_achievement_description_bane_of_the_dark: str
    lang_achievement_description_bundles_of_joy: str
    lang_achievement_description_cat_coach: str
    lang_achievement_description_catalog_collector: str
    lang_achievement_description_challenger_of_the_void: str
    lang_achievement_description_champion_of_light: str
    lang_achievement_description_citizen_of_the_wildwood: str
    lang_achievement_description_classy_cat: str
    lang_achievement_description_collector_of_ancient_treasure: str
    lang_achievement_description_conqueror: str
    lang_achievement_description_cryptic_crawler: str
    lang_achievement_description_deep_dweller: str
    lang_achievement_description_empathy: str
    lang_achievement_description_expert_forager: str
    lang_achievement_description_expert_hunter: str
    lang_achievement_description_fun_feline: str
    lang_achievement_description_green_thumb: str
    lang_achievement_description_how_romantic: str
    lang_achievement_description_humble_beginnings: str
    lang_achievement_description_in_the_cards: str
    lang_achievement_description_interior_design: str
    lang_achievement_description_its_dark_down_here: str
    lang_achievement_description_jack_of_all_trades: str
    lang_achievement_description_lend_a_paw: str
    lang_achievement_description_light_and_life: str
    lang_achievement_description_mastery: str
    lang_achievement_description_matchmaker: str
    lang_achievement_description_mole_friend: str
    lang_achievement_description_neighborly_negotiations: str
    lang_achievement_description_novice_forager: str
    lang_achievement_description_novice_hunter: str
    lang_achievement_description_novice_of_the_wildwood: str
    lang_achievement_description_patron_of_the_arts: str
    lang_achievement_description_peerless_prey: str
    lang_achievement_description_philanthropy: str
    lang_achievement_description_plant_proliferator: str
    lang_achievement_description_popularity_contest: str
    lang_achievement_description_population_boom: str
    lang_achievement_description_resident_of_the_wildwood: str
    lang_achievement_description_restorer_of_the_wildwood: str
    lang_achievement_description_risky_pickings: str
    lang_achievement_description_seedy: str
    lang_achievement_description_seeker_of_ancient_treasure: str
    lang_achievement_description_skirmisher: str
    lang_achievement_description_soldier: str
    lang_achievement_description_sparkling_stone: str
    lang_achievement_description_standing_army: str
    lang_achievement_description_stylish: str
    lang_achievement_description_talent_acquisition: str
    lang_achievement_description_the_cats_meow: str
    lang_achievement_description_treasure_trove: str
    lang_achievement_description_tying_the_knot: str
    lang_achievement_description_veteran_forager: str
    lang_achievement_description_veteran_hunter: str
    lang_achievement_description_withered_heart: str
    lang_achievement_description_world_domination: str
    lang_achievement_locked: str
    lang_achievement_name_abundance: str
    lang_achievement_name_accent_piece: str
    lang_achievement_name_adept_of_the_abyss: str
    lang_achievement_name_archaeologist_of_ancient_treasure: str
    lang_achievement_name_bane_of_the_dark: str
    lang_achievement_name_bundles_of_joy: str
    lang_achievement_name_cat_coach: str
    lang_achievement_name_catalog_collector: str
    lang_achievement_name_challenger_of_the_void: str
    lang_achievement_name_champion_of_light: str
    lang_achievement_name_citizen_of_the_wildwood: str
    lang_achievement_name_classy_cat: str
    lang_achievement_name_collector_of_ancient_treasure: str
    lang_achievement_name_conqueror: str
    lang_achievement_name_cryptic_crawler: str
    lang_achievement_name_deep_dweller: str
    lang_achievement_name_empathy: str
    lang_achievement_name_expert_forager: str
    lang_achievement_name_expert_hunter: str
    lang_achievement_name_fun_feline: str
    lang_achievement_name_green_thumb: str
    lang_achievement_name_how_romantic: str
    lang_achievement_name_humble_beginnings: str
    lang_achievement_name_in_the_cards: str
    lang_achievement_name_interior_design: str
    lang_achievement_name_its_dark_down_here: str
    lang_achievement_name_jack_of_all_trades: str
    lang_achievement_name_lend_a_paw: str
    lang_achievement_name_light_and_life: str
    lang_achievement_name_mastery: str
    lang_achievement_name_matchmaker: str
    lang_achievement_name_mole_friend: str
    lang_achievement_name_neighborly_negotiations: str
    lang_achievement_name_novice_forager: str
    lang_achievement_name_novice_hunter: str
    lang_achievement_name_novice_of_the_wildwood: str
    lang_achievement_name_patron_of_the_arts: str
    lang_achievement_name_peerless_prey: str
    lang_achievement_name_philanthropy: str
    lang_achievement_name_plant_proliferator: str
    lang_achievement_name_popularity_contest: str
    lang_achievement_name_population_boom: str
    lang_achievement_name_resident_of_the_wildwood: str
    lang_achievement_name_restorer_of_the_wildwood: str
    lang_achievement_name_risky_pickings: str
    lang_achievement_name_seedy: str
    lang_achievement_name_seeker_of_ancient_treasure: str
    lang_achievement_name_skirmisher: str
    lang_achievement_name_soldier: str
    lang_achievement_name_sparkling_stone: str
    lang_achievement_name_standing_army: str
    lang_achievement_name_stylish: str
    lang_achievement_name_talent_acquisition: str
    lang_achievement_name_the_cats_meow: str
    lang_achievement_name_treasure_trove: str
    lang_achievement_name_tying_the_knot: str
    lang_achievement_name_veteran_forager: str
    lang_achievement_name_veteran_hunter: str
    lang_achievement_name_withered_heart: str
    lang_achievement_name_world_domination: str
    lang_achievement_progress: str
    lang_achievement_reward: str
    lang_achievement_unlocked: str
    lang_achievements_disabled_tip: str
    lang_achievements_title: str
    lang_achievements_tooltip: str
    lang_actions: str
    lang_active_trait: str
    lang_adaptive_trait_description: str
    lang_adaptive_trait_name: str
    lang_add_custom_color: str
    lang_add_floor: str
    lang_advance_1_hour: str
    lang_advice_confrontation: str
    lang_advice_dark_portents: str
    lang_advice_reclamation_dr1: str
    lang_advice_reclamation_dr2: str
    lang_advice_reclamation_dr3: str
    lang_advice_reclamation_dr4: str
    lang_advice_reclamation_recruit: str
    lang_all_accessories: str
    lang_all_cats_unlocked: str
    lang_all_collections: str
    lang_all_furniture: str
    lang_all_squads_assigned: str
    lang_all_squads_assigned_barracks_tip: str
    lang_alpha: str
    lang_alt: str
    lang_alternative_font: str
    lang_alternative_font_tooltip: str
    lang_am: str
    lang_and: str
    lang_appearance: str
    lang_apply: str
    lang_apply_changes: str
    lang_apply_changes_title: str
    lang_arachnids: str
    lang_arachnids_tooltip: str
    lang_ask_about_task: str
    lang_ask_about_task_title: str
    lang_assign_bed: str
    lang_assign_squad: str
    lang_assign_squad_colony_territory: str
    lang_assign_squad_enemy_territory: str
    lang_assign_squads_title: str
    lang_attack_pounce: str
    lang_audio_options: str
    lang_audio_options_title: str
    lang_audio_options_tooltip: str
    lang_auto_run: str
    lang_auto_run_tooltip: str
    lang_autosave: str
    lang_autosave_tooltip: str
    lang_autumn: str
    lang_autumn1record: str
    lang_autumn2record: str
    lang_autumn3record: str
    lang_autumn_1: str
    lang_autumn_10: str
    lang_autumn_2: str
    lang_autumn_3: str
    lang_autumn_4: str
    lang_autumn_5: str
    lang_autumn_6: str
    lang_autumn_7: str
    lang_autumn_8: str
    lang_autumn_9: str
    lang_autumn_carving: str
    lang_autumnfestivalrecord: str
    lang_available_construction_projects: str
    lang_back: str
    lang_barracks_upgrade_i: str
    lang_barracks_upgrade_i_tooltip: str
    lang_barracks_upgrade_ii: str
    lang_barracks_upgrade_ii_tooltip: str
    lang_barracks_upgrade_iii: str
    lang_barracks_upgrade_iii_tooltip: str
    lang_basalt_floor: str
    lang_basalt_path: str
    lang_basalt_wall: str
    lang_battle_reward: str
    lang_battle_won: str
    lang_bed_assign_prompt: str
    lang_bed_assigned: str
    lang_bed_leave: str
    lang_bed_no_sleep_bonuses: str
    lang_bed_save_game: str
    lang_bed_sleep: str
    lang_bed_use: str
    lang_beta: str
    lang_birthday: str
    lang_birthday_event_structure: str
    lang_blizzard: str
    lang_blue_initial: str
    lang_body_type: str
    lang_body_type_ears_angled: str
    lang_body_type_ears_fluffy: str
    lang_body_type_ears_huge: str
    lang_body_type_ears_large: str
    lang_body_type_ears_missing: str
    lang_body_type_ears_none: str
    lang_body_type_ears_shorthair: str
    lang_body_type_ears_small: str
    lang_body_type_ears_tipped: str
    lang_body_type_ears_torn: str
    lang_body_type_face_fluffy: str
    lang_body_type_face_large: str
    lang_body_type_face_shorthair: str
    lang_body_type_face_slender: str
    lang_body_type_tail_bobtail: str
    lang_body_type_tail_curly: str
    lang_body_type_tail_downward: str
    lang_body_type_tail_fluffy_down: str
    lang_body_type_tail_fluffy_up: str
    lang_body_type_tail_kinked: str
    lang_body_type_tail_short: str
    lang_body_type_tail_stump: str
    lang_body_type_tail_upward: str
    lang_body_type_title: str
    lang_body_type_torso_fluffy: str
    lang_body_type_torso_large: str
    lang_body_type_torso_shorthair: str
    lang_body_type_torso_slender: str
    lang_boss_defeated_dialog: str
    lang_boss_hp: str
    lang_break_all_rocks: str
    lang_brick_floor: str
    lang_brick_path: str
    lang_brick_wall: str
    lang_buddy_cannot_follow_dialog: str
    lang_buddy_cannot_level_up_not_enough_xp_dialog: str
    lang_buddy_cannot_recruit_from_social_panel_dialog: str
    lang_buddy_level: str
    lang_buddy_level_up: str
    lang_buddy_level_up_confirmation_dialog: str
    lang_buddy_level_up_tip_subtext: str
    lang_buddy_leveled_up_dialog: str
    lang_buddy_ready_to_level_up: str
    lang_buddy_stats_title: str
    lang_buddy_system_info: str
    lang_buddy_up: str
    lang_buddy_xp_gain_item_cannot_use_dialog: str
    lang_buddy_xp_progress: str
    lang_build_menu: str
    lang_build_menu_buildings: str
    lang_build_menu_catalog: str
    lang_build_menu_catalog_title: str
    lang_build_menu_close_hint: str
    lang_build_menu_decor: str
    lang_build_menu_error_buildings_not_placed: str
    lang_build_menu_error_no_founders_stone: str
    lang_build_menu_error_utility_object_not_placed: str
    lang_build_menu_founders_stone_required: str
    lang_build_menu_no_valid_path_building: str
    lang_build_menu_no_valid_path_east: str
    lang_build_menu_no_valid_path_north: str
    lang_build_menu_no_valid_path_south: str
    lang_build_menu_no_valid_path_taskboard: str
    lang_build_menu_no_valid_path_west: str
    lang_build_menu_object_required_tip: str
    lang_build_menu_paths: str
    lang_build_menu_tutorial_dialog_begin: str
    lang_build_menu_tutorial_dialog_end: str
    lang_build_menu_utility: str
    lang_build_menu_water: str
    lang_bundle_hint: str
    lang_bundle_item_already_donated_dialog: str
    lang_bundle_item_cannot_donate_dialog: str
    lang_bundle_label_gardening: str
    lang_bundle_label_museum: str
    lang_bundle_label_squads: str
    lang_burn_rate: str
    lang_bush_wall: str
    lang_button_tooltip_drop: str
    lang_button_tooltip_eat: str
    lang_button_tooltip_fertilize: str
    lang_button_tooltip_hold: str
    lang_button_tooltip_pick_up: str
    lang_button_tooltip_pounce: str
    lang_button_tooltip_put_away: str
    lang_button_tooltip_sow: str
    lang_button_tooltip_talk: str
    lang_button_tooltip_uproot: str
    lang_button_tooltip_use: str
    lang_buy: str
    lang_buy_how_many: str
    lang_buy_items: str
    lang_buy_items_title: str
    lang_buy_multiple: str
    lang_buy_quantity: str
    lang_bye: str
    lang_calendar_no_events: str
    lang_calendar_title: str
    lang_camera_style: str
    lang_camera_style_tooltip: str
    lang_cancel: str
    lang_cancel_back: str
    lang_cancel_back_alt: str
    lang_cancel_task: str
    lang_cancel_task_title: str
    lang_cannot_apply_changes_controller_conflict: str
    lang_cannot_apply_changes_key_conflict: str
    lang_cannot_assign_squad_there: str
    lang_cannot_craft_missing_prerequisite: str
    lang_cannot_craft_no_ingredients: str
    lang_cannot_craft_no_inventory_space: str
    lang_cannot_detach_mail: str
    lang_cannot_equip_skill_dialog: str
    lang_cannot_modify_skills_not_in_den: str
    lang_cannot_retrain_while_following_dialog: str
    lang_cannot_save_dialog: str
    lang_cannot_unlock_skill_dialog: str
    lang_cannot_upgrade_max_rank_dialog: str
    lang_cannot_upgrade_skill_dialog: str
    lang_cannot_use_skill_dialog: str
    lang_caring_trait_description: str
    lang_caring_trait_name: str
    lang_carving_ask: str
    lang_carving_correct: str
    lang_carving_failure: str
    lang_carving_incorrect: str
    lang_carving_leave_dialog: str
    lang_carving_no: str
    lang_carving_prepare_questions_dialog: str
    lang_carving_question_1: str
    lang_carving_question_2: str
    lang_carving_question_3: str
    lang_carving_question_4: str
    lang_carving_question_5: str
    lang_carving_question_text_0: str
    lang_carving_question_text_0_option_0: str
    lang_carving_question_text_0_option_1: str
    lang_carving_question_text_0_option_2: str
    lang_carving_question_text_1: str
    lang_carving_question_text_10: str
    lang_carving_question_text_11: str
    lang_carving_question_text_12: str
    lang_carving_question_text_13: str
    lang_carving_question_text_14: str
    lang_carving_question_text_14_option_0: str
    lang_carving_question_text_14_option_1: str
    lang_carving_question_text_14_option_2: str
    lang_carving_question_text_15: str
    lang_carving_question_text_15_option_0: str
    lang_carving_question_text_15_option_1: str
    lang_carving_question_text_15_option_2: str
    lang_carving_question_text_16: str
    lang_carving_question_text_16_option_0: str
    lang_carving_question_text_16_option_1: str
    lang_carving_question_text_16_option_2: str
    lang_carving_question_text_17: str
    lang_carving_question_text_18: str
    lang_carving_question_text_19: str
    lang_carving_question_text_19_option_0: str
    lang_carving_question_text_19_option_1: str
    lang_carving_question_text_19_option_2: str
    lang_carving_question_text_1_option_0: str
    lang_carving_question_text_1_option_1: str
    lang_carving_question_text_1_option_2: str
    lang_carving_question_text_2: str
    lang_carving_question_text_20: str
    lang_carving_question_text_21: str
    lang_carving_question_text_22: str
    lang_carving_question_text_22_option_0: str
    lang_carving_question_text_22_option_1: str
    lang_carving_question_text_22_option_2: str
    lang_carving_question_text_23: str
    lang_carving_question_text_24: str
    lang_carving_question_text_25: str
    lang_carving_question_text_25_option_0: str
    lang_carving_question_text_25_option_1: str
    lang_carving_question_text_25_option_2: str
    lang_carving_question_text_26: str
    lang_carving_question_text_26_option_0: str
    lang_carving_question_text_26_option_1: str
    lang_carving_question_text_26_option_2: str
    lang_carving_question_text_27: str
    lang_carving_question_text_27_option_0: str
    lang_carving_question_text_27_option_1: str
    lang_carving_question_text_27_option_2: str
    lang_carving_question_text_28: str
    lang_carving_question_text_29: str
    lang_carving_question_text_29_option_0: str
    lang_carving_question_text_29_option_1: str
    lang_carving_question_text_29_option_2: str
    lang_carving_question_text_2_option_0: str
    lang_carving_question_text_2_option_1: str
    lang_carving_question_text_2_option_2: str
    lang_carving_question_text_3: str
    lang_carving_question_text_30: str
    lang_carving_question_text_30_option_0: str
    lang_carving_question_text_30_option_1: str
    lang_carving_question_text_30_option_2: str
    lang_carving_question_text_3_option_0: str
    lang_carving_question_text_3_option_1: str
    lang_carving_question_text_3_option_2: str
    lang_carving_question_text_4: str
    lang_carving_question_text_4_option_0: str
    lang_carving_question_text_4_option_1: str
    lang_carving_question_text_4_option_2: str
    lang_carving_question_text_5: str
    lang_carving_question_text_5_option_0: str
    lang_carving_question_text_5_option_1: str
    lang_carving_question_text_5_option_2: str
    lang_carving_question_text_6: str
    lang_carving_question_text_6_option_0: str
    lang_carving_question_text_6_option_1: str
    lang_carving_question_text_6_option_2: str
    lang_carving_question_text_7: str
    lang_carving_question_text_7_option_0: str
    lang_carving_question_text_7_option_1: str
    lang_carving_question_text_7_option_2: str
    lang_carving_question_text_8: str
    lang_carving_question_text_9: str
    lang_carving_questions_start: str
    lang_carving_success: str
    lang_carving_yes: str
    lang_cat_fish_river_choose_dialog: str
    lang_cat_fish_river_pre_dialog: str
    lang_cat_meows: str
    lang_cat_meows_tooltip: str
    lang_cat_voice_1: str
    lang_cat_voice_10: str
    lang_cat_voice_2: str
    lang_cat_voice_3: str
    lang_cat_voice_4: str
    lang_cat_voice_5: str
    lang_cat_voice_6: str
    lang_cat_voice_7: str
    lang_cat_voice_8: str
    lang_cat_voice_9: str
    lang_catnip_stockpile: str
    lang_cave_wall: str
    lang_celestial_floor: str
    lang_celestial_path: str
    lang_celestial_wall: str
    lang_cfr_cat: str
    lang_cfr_fish: str
    lang_cfr_player_lose_dialog: str
    lang_cfr_player_tie_dialog: str
    lang_cfr_player_win_dialog: str
    lang_cfr_river: str
    lang_change_accessories: str
    lang_change_body_type: str
    lang_change_eye_color: str
    lang_change_ground_type: str
    lang_change_ground_type_title: str
    lang_change_style: str
    lang_channel_name_news: str
    lang_channel_name_visions: str
    lang_channel_name_weather: str
    lang_channel_name_wisdom: str
    lang_choose_here: str
    lang_close: str
    lang_close_collections: str
    lang_close_inventory: str
    lang_close_inventory_tooltip: str
    lang_close_map: str
    lang_close_options: str
    lang_coat_belly: str
    lang_coat_bengal: str
    lang_coat_black: str
    lang_coat_black_calico: str
    lang_coat_black_tabby: str
    lang_coat_blue: str
    lang_coat_blue_tabby: str
    lang_coat_brown: str
    lang_coat_brown_calico: str
    lang_coat_brown_tabby: str
    lang_coat_category_base: str
    lang_coat_category_details: str
    lang_coat_category_ears: str
    lang_coat_category_patterns_i: str
    lang_coat_category_patterns_ii: str
    lang_coat_category_paws: str
    lang_coat_cream: str
    lang_coat_cream_tabby: str
    lang_coat_dark_tortoiseshell: str
    lang_coat_dilute_tortoiseshell: str
    lang_coat_ears_inner: str
    lang_coat_grey: str
    lang_coat_grey_and_white: str
    lang_coat_grey_tabby: str
    lang_coat_head: str
    lang_coat_head_stripes: str
    lang_coat_left_ear: str
    lang_coat_legs: str
    lang_coat_light_brown_tabby: str
    lang_coat_lilac: str
    lang_coat_lilac_tabby: str
    lang_coat_muzzle: str
    lang_coat_new: str
    lang_coat_nose: str
    lang_coat_orange: str
    lang_coat_orange_and_white: str
    lang_coat_orange_calico: str
    lang_coat_orange_tabby: str
    lang_coat_patches_one: str
    lang_coat_patches_two: str
    lang_coat_paw_back_left: str
    lang_coat_paw_back_right: str
    lang_coat_paw_front_left: str
    lang_coat_paw_front_right: str
    lang_coat_point: str
    lang_coat_right_ear: str
    lang_coat_rosettes: str
    lang_coat_ruddy: str
    lang_coat_siamese: str
    lang_coat_silver: str
    lang_coat_silver_tabby: str
    lang_coat_speckles: str
    lang_coat_stripes: str
    lang_coat_stripes_two: str
    lang_coat_studio_title: str
    lang_coat_tail: str
    lang_coat_tail_tip: str
    lang_coat_torso: str
    lang_coat_tuxedo: str
    lang_coat_white: str
    lang_coat_white_bengal: str
    lang_coin_toss: str
    lang_collections_bugs: str
    lang_collections_category_tooltip: str
    lang_collections_curios: str
    lang_collections_hostile_prey: str
    lang_collections_locked_tooltip: str
    lang_collections_miscellaneous: str
    lang_collections_plants: str
    lang_collections_power_paws: str
    lang_collections_prey: str
    lang_collections_title: str
    lang_collections_youve_caught: str
    lang_collections_youve_collected: str
    lang_collections_youve_defeated: str
    lang_collections_youve_harvested: str
    lang_collections_youve_identified: str
    lang_colony_emblem: str
    lang_colony_full_name_structure: str
    lang_colony_full_name_structure_capitalized_with_article: str
    lang_colony_full_name_structure_with_article: str
    lang_colony_name: str
    lang_colony_options: str
    lang_colony_options_post_dialog: str
    lang_colony_options_post_same_dialog: str
    lang_colony_options_pre_dialog: str
    lang_colony_options_title: str
    lang_colony_random_name_eight: str
    lang_colony_random_name_eighteen: str
    lang_colony_random_name_eleven: str
    lang_colony_random_name_fifteen: str
    lang_colony_random_name_five: str
    lang_colony_random_name_four: str
    lang_colony_random_name_fourteen: str
    lang_colony_random_name_fourty: str
    lang_colony_random_name_nine: str
    lang_colony_random_name_nineteen: str
    lang_colony_random_name_one: str
    lang_colony_random_name_seven: str
    lang_colony_random_name_seventeen: str
    lang_colony_random_name_six: str
    lang_colony_random_name_sixteen: str
    lang_colony_random_name_ten: str
    lang_colony_random_name_thirteen: str
    lang_colony_random_name_thirty: str
    lang_colony_random_name_thirtyeight: str
    lang_colony_random_name_thirtyfive: str
    lang_colony_random_name_thirtyfour: str
    lang_colony_random_name_thirtynine: str
    lang_colony_random_name_thirtyone: str
    lang_colony_random_name_thirtyseven: str
    lang_colony_random_name_thirtysix: str
    lang_colony_random_name_thirtythree: str
    lang_colony_random_name_thirtytwo: str
    lang_colony_random_name_three: str
    lang_colony_random_name_twelve: str
    lang_colony_random_name_twenty: str
    lang_colony_random_name_twentyeight: str
    lang_colony_random_name_twentyfive: str
    lang_colony_random_name_twentyfour: str
    lang_colony_random_name_twentynine: str
    lang_colony_random_name_twentyone: str
    lang_colony_random_name_twentyseven: str
    lang_colony_random_name_twentysix: str
    lang_colony_random_name_twentythree: str
    lang_colony_random_name_twentytwo: str
    lang_colony_random_name_two: str
    lang_colony_stockpiles_title: str
    lang_colony_title: str
    lang_colony_title_eight: str
    lang_colony_title_eight_with_article: str
    lang_colony_title_eight_with_definite_article: str
    lang_colony_title_eight_with_demonstrative_article: str
    lang_colony_title_eight_with_indefinite_article: str
    lang_colony_title_eighteen: str
    lang_colony_title_eighteen_with_article: str
    lang_colony_title_eighteen_with_definite_article: str
    lang_colony_title_eighteen_with_demonstrative_article: str
    lang_colony_title_eighteen_with_indefinite_article: str
    lang_colony_title_eleven: str
    lang_colony_title_eleven_with_article: str
    lang_colony_title_eleven_with_definite_article: str
    lang_colony_title_eleven_with_demonstrative_article: str
    lang_colony_title_eleven_with_indefinite_article: str
    lang_colony_title_fifteen: str
    lang_colony_title_fifteen_with_article: str
    lang_colony_title_fifteen_with_definite_article: str
    lang_colony_title_fifteen_with_demonstrative_article: str
    lang_colony_title_fifteen_with_indefinite_article: str
    lang_colony_title_five: str
    lang_colony_title_five_with_article: str
    lang_colony_title_five_with_definite_article: str
    lang_colony_title_five_with_demonstrative_article: str
    lang_colony_title_five_with_indefinite_article: str
    lang_colony_title_four: str
    lang_colony_title_four_with_article: str
    lang_colony_title_four_with_definite_article: str
    lang_colony_title_four_with_demonstrative_article: str
    lang_colony_title_four_with_indefinite_article: str
    lang_colony_title_fourteen: str
    lang_colony_title_fourteen_with_article: str
    lang_colony_title_fourteen_with_definite_article: str
    lang_colony_title_fourteen_with_demonstrative_article: str
    lang_colony_title_fourteen_with_indefinite_article: str
    lang_colony_title_nine: str
    lang_colony_title_nine_with_article: str
    lang_colony_title_nine_with_definite_article: str
    lang_colony_title_nine_with_demonstrative_article: str
    lang_colony_title_nine_with_indefinite_article: str
    lang_colony_title_nineteen: str
    lang_colony_title_nineteen_with_article: str
    lang_colony_title_nineteen_with_definite_article: str
    lang_colony_title_nineteen_with_demonstrative_article: str
    lang_colony_title_nineteen_with_indefinite_article: str
    lang_colony_title_one: str
    lang_colony_title_one_with_article: str
    lang_colony_title_one_with_definite_article: str
    lang_colony_title_one_with_demonstrative_article: str
    lang_colony_title_one_with_indefinite_article: str
    lang_colony_title_seven: str
    lang_colony_title_seven_with_article: str
    lang_colony_title_seven_with_definite_article: str
    lang_colony_title_seven_with_demonstrative_article: str
    lang_colony_title_seven_with_indefinite_article: str
    lang_colony_title_seventeen: str
    lang_colony_title_seventeen_with_article: str
    lang_colony_title_seventeen_with_definite_article: str
    lang_colony_title_seventeen_with_demonstrative_article: str
    lang_colony_title_seventeen_with_indefinite_article: str
    lang_colony_title_six: str
    lang_colony_title_six_with_article: str
    lang_colony_title_six_with_definite_article: str
    lang_colony_title_six_with_demonstrative_article: str
    lang_colony_title_six_with_indefinite_article: str
    lang_colony_title_sixteen: str
    lang_colony_title_sixteen_with_article: str
    lang_colony_title_sixteen_with_definite_article: str
    lang_colony_title_sixteen_with_demonstrative_article: str
    lang_colony_title_sixteen_with_indefinite_article: str
    lang_colony_title_ten: str
    lang_colony_title_ten_with_article: str
    lang_colony_title_ten_with_definite_article: str
    lang_colony_title_ten_with_demonstrative_article: str
    lang_colony_title_ten_with_indefinite_article: str
    lang_colony_title_thirteen: str
    lang_colony_title_thirteen_with_article: str
    lang_colony_title_thirteen_with_definite_article: str
    lang_colony_title_thirteen_with_demonstrative_article: str
    lang_colony_title_thirteen_with_indefinite_article: str
    lang_colony_title_three: str
    lang_colony_title_three_with_article: str
    lang_colony_title_three_with_definite_article: str
    lang_colony_title_three_with_demonstrative_article: str
    lang_colony_title_three_with_indefinite_article: str
    lang_colony_title_twelve: str
    lang_colony_title_twelve_with_article: str
    lang_colony_title_twelve_with_definite_article: str
    lang_colony_title_twelve_with_demonstrative_article: str
    lang_colony_title_twelve_with_indefinite_article: str
    lang_colony_title_twenty: str
    lang_colony_title_twenty_with_article: str
    lang_colony_title_twenty_with_definite_article: str
    lang_colony_title_twenty_with_demonstrative_article: str
    lang_colony_title_twenty_with_indefinite_article: str
    lang_colony_title_twentyfour: str
    lang_colony_title_twentyfour_with_article: str
    lang_colony_title_twentyfour_with_definite_article: str
    lang_colony_title_twentyfour_with_demonstrative_article: str
    lang_colony_title_twentyfour_with_indefinite_article: str
    lang_colony_title_twentyone: str
    lang_colony_title_twentyone_with_article: str
    lang_colony_title_twentyone_with_definite_article: str
    lang_colony_title_twentyone_with_demonstrative_article: str
    lang_colony_title_twentyone_with_indefinite_article: str
    lang_colony_title_twentythree: str
    lang_colony_title_twentythree_with_article: str
    lang_colony_title_twentythree_with_definite_article: str
    lang_colony_title_twentythree_with_demonstrative_article: str
    lang_colony_title_twentythree_with_indefinite_article: str
    lang_colony_title_twentytwo: str
    lang_colony_title_twentytwo_with_article: str
    lang_colony_title_twentytwo_with_definite_article: str
    lang_colony_title_twentytwo_with_demonstrative_article: str
    lang_colony_title_twentytwo_with_indefinite_article: str
    lang_colony_title_two: str
    lang_colony_title_two_with_article: str
    lang_colony_title_two_with_definite_article: str
    lang_colony_title_two_with_demonstrative_article: str
    lang_colony_title_two_with_indefinite_article: str
    lang_color_palette_title: str
    lang_color_style: str
    lang_color_style_tooltip: str
    lang_come_with_me: str
    lang_coming_soon_dialog: str
    lang_commit_changes: str
    lang_common: str
    lang_community_support_dialog_generic: str
    lang_complete_all_bundles: str
    lang_complete_main_story: str
    lang_complete_task: str
    lang_complete_task_title: str
    lang_completed_construction_projects_title: str
    lang_concrete_floor: str
    lang_concrete_path: str
    lang_confirm: str
    lang_confirm_build_menu_dialog: str
    lang_confirm_changes: str
    lang_confirm_floorplan: str
    lang_confirm_kitten_details_title: str
    lang_confirm_select: str
    lang_confirm_select_alt: str
    lang_construct_it: str
    lang_construction_confirmed_dialog: str
    lang_construction_project_cannot_afford_dialog: str
    lang_construction_project_confirm_purchase: str
    lang_construction_projects: str
    lang_construction_projects_tip: str
    lang_construction_projects_title: str
    lang_continue: str
    lang_controller: str
    lang_controller_plus_button: str = dataclasses.field(
        metadata=dataclasses_json.config(field_name="lang_controller_+_button")
    )
    lang_controller_minus_button: str = dataclasses.field(
        metadata=dataclasses_json.config(field_name="lang_controller_-_button")
    )
    lang_controller_a: str
    lang_controller_b: str
    lang_controller_down_button: str
    lang_controller_dpad_down: str
    lang_controller_dpad_left: str
    lang_controller_dpad_right: str
    lang_controller_dpad_up: str
    lang_controller_l_button: str
    lang_controller_left_button: str
    lang_controller_left_shoulder: str
    lang_controller_left_stick: str
    lang_controller_left_stick_down: str
    lang_controller_left_stick_left: str
    lang_controller_left_stick_press: str
    lang_controller_left_stick_right: str
    lang_controller_left_stick_up: str
    lang_controller_left_trigger: str
    lang_controller_none: str
    lang_controller_r_button: str
    lang_controller_right_button: str
    lang_controller_right_shoulder: str
    lang_controller_right_stick: str
    lang_controller_right_stick_down: str
    lang_controller_right_stick_left: str
    lang_controller_right_stick_press: str
    lang_controller_right_stick_right: str
    lang_controller_right_stick_up: str
    lang_controller_right_trigger: str
    lang_controller_select: str
    lang_controller_start: str
    lang_controller_title: str
    lang_controller_up_button: str
    lang_controller_x: str
    lang_controller_y: str
    lang_controller_zl: str
    lang_controller_zr: str
    lang_copy_confirmation: str
    lang_copy_files: str
    lang_copy_files_prompt: str
    lang_copy_files_title: str
    lang_cost: str
    lang_crafting_no_recipes_tip: str
    lang_crafting_results_title: str
    lang_crafting_select_tip: str
    lang_crafting_title: str
    lang_create_your_kitty_title: str
    lang_credits: str
    lang_credits_art: str
    lang_credits_backers: str
    lang_credits_chief_executive_dog: str
    lang_credits_composer: str
    lang_credits_concept_artist: str
    lang_credits_contributors: str
    lang_credits_end: str
    lang_credits_founders: str
    lang_credits_highscore: str
    lang_credits_key_art: str
    lang_credits_lead_developer: str
    lang_credits_legal: str
    lang_credits_logo_design: str
    lang_credits_marketing_coordinator: str
    lang_credits_music_and_sound: str
    lang_credits_nintendo_switch: str
    lang_credits_pianist: str
    lang_credits_pixel_artist: str
    lang_credits_portrait_artist: str
    lang_credits_resident_cat_intern: str
    lang_credits_saxophonist: str
    lang_credits_score: str
    lang_credits_senior_resident_cat: str
    lang_credits_shader_tutorials: str
    lang_credits_special_thanks: str
    lang_credits_title: str
    lang_credits_trailer_animation: str
    lang_credits_trailer_voiceover: str
    lang_credits_visionary: str
    lang_creditsrecord: str
    lang_cultivation: str
    lang_cultivation_tooltip: str
    lang_curator_10_curios_post_dialog: str
    lang_curator_20_curios_post_dialog: str
    lang_curator_30_curios_post_dialog: str
    lang_curator_3_curios_post_dialog: str
    lang_curator_begin_dialog: str
    lang_curator_end_dialog: str
    lang_curator_end_no_curios_remaining_dialog: str
    lang_curio_already_donated: str
    lang_curio_donate_ask_dialog: str
    lang_curio_identification_title: str
    lang_curio_item_donated: str
    lang_curio_item_not_donated: str
    lang_curio_not_yet_donated: str
    lang_curios_help_dialog: str
    lang_customize: str
    lang_daily_battle_alert: str
    lang_dark_portents_dialog_0: str
    lang_dark_portents_dialog_1: str
    lang_dark_portents_dialog_2: str
    lang_dark_portents_dialog_3: str
    lang_dark_portents_dialog_4: str
    lang_dark_portents_dialog_5: str
    lang_dark_portents_dialog_6: str
    lang_dark_portents_dialog_7: str
    lang_dark_portents_dialog_8: str
    lang_dark_ruins_available_tip_intro_dialog: str
    lang_dark_ruins_community_points_not_yet_met_dialog: str
    lang_dark_ruins_intro_dialog_0: str
    lang_dark_ruins_intro_dialog_1: str
    lang_dark_ruins_intro_dialog_2: str
    lang_dark_ruins_intro_dialog_3: str
    lang_dark_ruins_intro_dialog_4: str
    lang_dark_ruins_unknown_dialog: str
    lang_dark_ruins_unlocked_dialog: str
    lang_dark_stairs_dialog: str
    lang_darkruinsrecord: str
    lang_day: str
    lang_death_dialog: str
    lang_decorative_brick_path: str
    lang_deep_water: str
    lang_default: str
    lang_delete_coat: str
    lang_delete_coat_title: str
    lang_delete_confirmation: str
    lang_delete_files: str
    lang_delete_files_prompt: str
    lang_delete_files_title: str
    lang_delicate_trait_description: str
    lang_delicate_trait_name: str
    lang_den_locked_married: str
    lang_den_renovation: str
    lang_descend_dark_stairs: str
    lang_dev_shop: str
    lang_dev_tools: str
    lang_dev_tools_title: str
    lang_diagnostics: str
    lang_diagnostics_title: str
    lang_diagnostics_tooltip: str
    lang_dialog_error: str
    lang_diamond_stockpile: str
    lang_dice_roll_choose_dialog: str
    lang_dice_roll_lose_dialog: str
    lang_dice_roll_pre_dialog: str
    lang_dice_roll_win_dialog: str
    lang_difficulty: str
    lang_difficulty_tooltip: str
    lang_dirt_floor_1: str
    lang_dirt_floor_2: str
    lang_dirt_path: str
    lang_discard: str
    lang_discard_changes: str
    lang_discard_changes_title: str
    lang_discard_floorplan_changes: str
    lang_dismiss_buddy: str
    lang_dismiss_buddy_title: str
    lang_do_not_enter_mine: str
    lang_do_not_leave_den_tutorial_dialog: str
    lang_do_not_purchase_item: str
    lang_do_not_sell_item: str
    lang_docked_gui: str
    lang_docked_gui_tooltip: str
    lang_doctor_cannot_afford_dialog: str
    lang_doctor_post_heal_dialog: str
    lang_doctor_respawn_dialog: str
    lang_dodge: str
    lang_donate: str
    lang_donate_all: str
    lang_donate_bendy_curio_dialog: str
    lang_donate_bouncy_curio_dialog: str
    lang_donate_cannot_sell_dialog: str
    lang_donate_cardboard_curio_dialog: str
    lang_donate_clicky_curio_dialog: str
    lang_donate_concave_curio_dialog: str
    lang_donate_cork_curio_dialog: str
    lang_donate_crinkly_curio_dialog: str
    lang_donate_curios_title: str
    lang_donate_everything: str
    lang_donate_everything_item: str
    lang_donate_festive_curio_dialog: str
    lang_donate_flexible_curio_dialog: str
    lang_donate_formal_curio_dialog: str
    lang_donate_fuzzy_curio_dialog: str
    lang_donate_hard_curio_dialog: str
    lang_donate_heavy_curio_dialog: str
    lang_donate_how_many: str
    lang_donate_inky_curio_dialog: str
    lang_donate_item: str
    lang_donate_items: str
    lang_donate_items_title: str
    lang_donate_jingly_curio_dialog: str
    lang_donate_long_curio_dialog: str
    lang_donate_marked_curio_dialog: str
    lang_donate_metal_curio_dialog: str
    lang_donate_plastic_curio_dialog: str
    lang_donate_pointy_curio_dialog: str
    lang_donate_quantity: str
    lang_donate_sell_dialog: str
    lang_donate_sell_everything_dialog: str
    lang_donate_sell_everything_invalid_dialog: str
    lang_donate_sell_everything_nothing_dialog: str
    lang_donate_shiny_curio_dialog: str
    lang_donate_small_curio_dialog: str
    lang_donate_soft_curio_dialog: str
    lang_donate_sparkly_curio_dialog: str
    lang_donate_springy_curio_dialog: str
    lang_donate_stockpile: str
    lang_donate_stretchy_curio_dialog: str
    lang_donate_sweet_curio_dialog: str
    lang_donate_wiry_curio_dialog: str
    lang_donate_wooden_curio_dialog: str
    lang_donate_wooly_curio_dialog: str
    lang_dont_draw: str
    lang_down_alt: str
    lang_dr1_post_dialog_0: str
    lang_dr1_post_dialog_1: str
    lang_dr1_post_dialog_2: str
    lang_dr1_post_dialog_3: str
    lang_dr1_post_dialog_4: str
    lang_dr2_post_dialog_0: str
    lang_dr2_post_dialog_1: str
    lang_dr3_post_dialog_0: str
    lang_dr3_post_dialog_1: str
    lang_dr3_post_dialog_2: str
    lang_dr4_post_dialog_0: str
    lang_dr4_post_dialog_1: str
    lang_dr4_post_dialog_2: str
    lang_dr4_post_dialog_3: str
    lang_dr4_post_dialog_4: str
    lang_dr_complete_dialog_0: str
    lang_dr_complete_dialog_1: str
    lang_dr_complete_dialog_2: str
    lang_dr_complete_dialog_3: str
    lang_dr_complete_dialog_4: str
    lang_dr_complete_dialog_5: str
    lang_dr_heal_tablet: str
    lang_dr_higher: str
    lang_dr_lower: str
    lang_dr_plaque_1: str
    lang_dr_plaque_10: str
    lang_dr_plaque_11: str
    lang_dr_plaque_12: str
    lang_dr_plaque_13: str
    lang_dr_plaque_14: str
    lang_dr_plaque_15: str
    lang_dr_plaque_2: str
    lang_dr_plaque_3: str
    lang_dr_plaque_4: str
    lang_dr_plaque_5: str
    lang_dr_plaque_6: str
    lang_dr_plaque_7: str
    lang_dr_plaque_8: str
    lang_dr_plaque_9: str
    lang_dr_symbol_hints: str
    lang_dr_symbol_hints2: str
    lang_dr_wing_complete_dialog: str
    lang_draw: str
    lang_draw_particles: str
    lang_draw_particles_tooltip: str
    lang_draw_reflections: str
    lang_draw_reflections_tooltip: str
    lang_draw_shadows: str
    lang_draw_shadows_tooltip: str
    lang_dream_sequence_dialog: str
    lang_ears: str
    lang_easy: str
    lang_eat_gross_text_five: str
    lang_eat_gross_text_four: str
    lang_eat_gross_text_one: str
    lang_eat_gross_text_three: str
    lang_eat_gross_text_two: str
    lang_eat_text_five: str
    lang_eat_text_four: str
    lang_eat_text_one: str
    lang_eat_text_three: str
    lang_eat_text_two: str
    lang_edit_coat: str
    lang_edit_coat_title: str
    lang_empty_do_not_translate: str
    lang_enhanced: str
    lang_enter_dark_ruins1: str
    lang_enter_dark_ruins2: str
    lang_enter_dark_ruins3: str
    lang_enter_dark_ruins4: str
    lang_enter_mine: str
    lang_enter_mine_25: str
    lang_enter_mine_50: str
    lang_enter_mine_75: str
    lang_enterprising_trait_description: str
    lang_enterprising_trait_name: str
    lang_entity_minigame_title: str
    lang_equip_accessories_tip: str
    lang_error_title: str
    lang_event_grant_item_dialog: str
    lang_event_grant_item_inventory_full_dialog: str
    lang_exit: str
    lang_exit_game: str
    lang_exit_game_title: str
    lang_eye_color: str
    lang_eye_color_different: str
    lang_eye_color_same: str
    lang_eye_color_title: str
    lang_face: str
    lang_false: str
    lang_fancy: str
    lang_festival_early_dialog: str
    lang_festival_early_dialog_autumn: str
    lang_festival_game_get_ready: str
    lang_festival_late_dialog: str
    lang_festival_late_dialog_autumn: str
    lang_festival_leave_no: str
    lang_festival_leave_prompt: str
    lang_festival_leave_yes: str
    lang_festival_minigame_over_dialog: str
    lang_festival_tokens: str
    lang_fg_dr5_dialog_0: str
    lang_fg_dr5_dialog_1: str
    lang_fg_dr5_dialog_2: str
    lang_fg_dr5_dialog_3: str
    lang_fg_dr5_dialog_post: str
    lang_fierce_trait_description: str
    lang_fierce_trait_name: str
    lang_fighter_npc_dialog_0: str
    lang_fighter_npc_dialog_1: str
    lang_fighter_npc_dialog_10: str
    lang_fighter_npc_dialog_11: str
    lang_fighter_npc_dialog_12: str
    lang_fighter_npc_dialog_13: str
    lang_fighter_npc_dialog_14: str
    lang_fighter_npc_dialog_15: str
    lang_fighter_npc_dialog_16: str
    lang_fighter_npc_dialog_17: str
    lang_fighter_npc_dialog_18: str
    lang_fighter_npc_dialog_19: str
    lang_fighter_npc_dialog_2: str
    lang_fighter_npc_dialog_20: str
    lang_fighter_npc_dialog_21: str
    lang_fighter_npc_dialog_22: str
    lang_fighter_npc_dialog_23: str
    lang_fighter_npc_dialog_24: str
    lang_fighter_npc_dialog_25: str
    lang_fighter_npc_dialog_26: str
    lang_fighter_npc_dialog_27: str
    lang_fighter_npc_dialog_28: str
    lang_fighter_npc_dialog_29: str
    lang_fighter_npc_dialog_3: str
    lang_fighter_npc_dialog_30: str
    lang_fighter_npc_dialog_31: str
    lang_fighter_npc_dialog_32: str
    lang_fighter_npc_dialog_33: str
    lang_fighter_npc_dialog_34: str
    lang_fighter_npc_dialog_35: str
    lang_fighter_npc_dialog_36: str
    lang_fighter_npc_dialog_37: str
    lang_fighter_npc_dialog_38: str
    lang_fighter_npc_dialog_39: str
    lang_fighter_npc_dialog_4: str
    lang_fighter_npc_dialog_40: str
    lang_fighter_npc_dialog_41: str
    lang_fighter_npc_dialog_42: str
    lang_fighter_npc_dialog_43: str
    lang_fighter_npc_dialog_44: str
    lang_fighter_npc_dialog_45: str
    lang_fighter_npc_dialog_46: str
    lang_fighter_npc_dialog_47: str
    lang_fighter_npc_dialog_48: str
    lang_fighter_npc_dialog_49: str
    lang_fighter_npc_dialog_5: str
    lang_fighter_npc_dialog_50: str
    lang_fighter_npc_dialog_51: str
    lang_fighter_npc_dialog_52: str
    lang_fighter_npc_dialog_53: str
    lang_fighter_npc_dialog_54: str
    lang_fighter_npc_dialog_55: str
    lang_fighter_npc_dialog_56: str
    lang_fighter_npc_dialog_57: str
    lang_fighter_npc_dialog_58: str
    lang_fighter_npc_dialog_59: str
    lang_fighter_npc_dialog_6: str
    lang_fighter_npc_dialog_60: str
    lang_fighter_npc_dialog_7: str
    lang_fighter_npc_dialog_8: str
    lang_fighter_npc_dialog_9: str
    lang_file_copied: str
    lang_file_copy_no_empty_slots: str
    lang_file_copy_yes: str
    lang_file_corrupt: str
    lang_file_delete_yes: str
    lang_file_deleted: str
    lang_file_overwrite_no: str
    lang_file_overwrite_yes: str
    lang_file_too_new: str
    lang_file_too_old: str
    lang_filter_all: str
    lang_filter_beds: str
    lang_filter_floor: str
    lang_filter_freestanding: str
    lang_filter_lights: str
    lang_filter_storage: str
    lang_filter_utility: str
    lang_filter_wall: str
    lang_floor_attachment: str
    lang_floor_surplus: str
    lang_fog: str
    lang_fog_and_rain: str
    lang_fog_and_snow: str
    lang_founders_stone_open_dialog: str
    lang_fps: str
    lang_fps_stabilization: str
    lang_fps_stabilization_tooltip: str
    lang_freestanding_attachment: str
    lang_furniture: str
    lang_furniture_catalog: str
    lang_furniture_catalog_title: str
    lang_furniture_label: str
    lang_furniture_tip: str
    lang_game_accept: str
    lang_game_autosave_confirmation: str
    lang_game_decline: str
    lang_game_decline_post_dialog: str
    lang_game_difficulty: str
    lang_game_options: str
    lang_game_options_title: str
    lang_game_over: str
    lang_game_paused: str
    lang_game_scale: str
    lang_game_scale_tooltip: str
    lang_game_title: str
    lang_garden_upgrade_tip: str
    lang_generic_married_kittens_0: str
    lang_generic_married_kittens_1: str
    lang_generic_married_kittens_2: str
    lang_generic_married_kittens_3: str
    lang_generic_married_kittens_4: str
    lang_gift_log_title: str
    lang_give_gift: str
    lang_glass_path: str
    lang_go_fullscreen: str
    lang_go_fullscreen_tooltip: str
    lang_go_windowed: str
    lang_go_windowed_tooltip: str
    lang_got_advice: str
    lang_got_item: str
    lang_grass_floor: str
    lang_grass_path: str
    lang_gravel_path: str
    lang_green_initial: str
    lang_ground_type_basalt: str
    lang_ground_type_basalt_tooltip: str
    lang_ground_type_dirt: str
    lang_ground_type_dirt_tooltip: str
    lang_ground_type_grass: str
    lang_ground_type_grass_tooltip: str
    lang_ground_type_rock: str
    lang_ground_type_rock_tooltip: str
    lang_ground_type_sand: str
    lang_ground_type_sand_tooltip: str
    lang_ground_type_swamp_grass: str
    lang_ground_type_swamp_grass_tooltip: str
    lang_gui_animations: str
    lang_gui_animations_tooltip: str
    lang_gui_scale: str
    lang_gui_scale_tooltip: str
    lang_hard: str
    lang_hardy_trait_description: str
    lang_hardy_trait_name: str
    lang_have: str
    lang_headlamp_upgrade_tip: str
    lang_heal_buddy: str
    lang_heal_cannot_heal_dialog: str
    lang_heal_full_dialog: str
    lang_heal_me: str
    lang_heal_me_fully: str
    lang_heal_me_partially: str
    lang_heal_partial_or_full_dialog: str
    lang_heal_pre_dialog: str
    lang_heavy_rain: str
    lang_heavy_snow: str
    lang_help: str
    lang_help_stockpile: str
    lang_herbs: str
    lang_herbs_perk_activated_notice: str
    lang_herbs_stockpile: str
    lang_herbs_stockpile_description: str
    lang_herbs_stockpile_perk_description: str
    lang_hide_gui: str
    lang_hotswap_left: str
    lang_hotswap_right: str
    lang_hsv: str
    lang_hue_initial: str
    lang_hunt_mode: str
    lang_hunt_mode_tooltip: str
    lang_hunting_compendium: str
    lang_hunting_compendium_tooltip: str
    lang_ice_floor: str
    lang_ice_path: str
    lang_identify: str
    lang_identify_curios_title: str
    lang_immersive: str
    lang_improved_roofing: str
    lang_improved_roofing_tooltip: str
    lang_influence_locked: str
    lang_influence_percentage: str
    lang_info: str
    lang_inspiring_trait_description: str
    lang_inspiring_trait_name: str
    lang_intro_progress_tooltip: str
    lang_intro_s1_t1: str
    lang_intro_s1_t2: str
    lang_intro_s1_t3: str
    lang_intro_s2_t1: str
    lang_intro_s2_t2: str
    lang_intro_s3_t1: str
    lang_intro_s3_t2: str
    lang_intro_s4_t1: str
    lang_intro_s4_t2: str
    lang_intro_s5_t1: str
    lang_intro_s5_t2: str
    lang_intro_s5_t3: str
    lang_intro_s5_t4: str
    lang_intro_s6_t1: str
    lang_intro_s6_t2: str
    lang_intro_s6_t3: str
    lang_intro_s7_t1: str
    lang_intro_s7_t2: str
    lang_intro_s8_t1: str
    lang_intro_s8_t2: str
    lang_intro_s8_t3: str
    lang_intro_skip_tooltip: str
    lang_invasion_defeated: str
    lang_invasion_subtext: str
    lang_invasion_text: str
    lang_inventory: str
    lang_inventory_holding: str
    lang_inventory_title: str
    lang_inventory_upgrade_tip: str
    lang_item_cannot_use_dialog: str
    lang_item_description_25_xp: str
    lang_item_description_35_mews: str
    lang_item_description_50_mole_cash: str
    lang_item_name_25_xp: str
    lang_item_name_35_mews: str
    lang_item_name_50_mole_cash: str
    lang_joy_con_controllers_title: str
    lang_jump: str
    lang_keen_trait_description: str
    lang_keen_trait_name: str
    lang_keep_designing: str
    lang_keep_redecorating: str
    lang_keyboard: str
    lang_keyboard_alphabet_do_not_translate: str
    lang_keyboard_alt: str
    lang_keyboard_backspace: str
    lang_keyboard_caps: str
    lang_keyboard_ctrl: str
    lang_keyboard_down: str
    lang_keyboard_enter: str
    lang_keyboard_esc: str
    lang_keyboard_left: str
    lang_keyboard_lowercase: str
    lang_keyboard_none: str
    lang_keyboard_right: str
    lang_keyboard_shift: str
    lang_keyboard_space: str
    lang_keyboard_special_characters: str
    lang_keyboard_tab: str
    lang_keyboard_title: str
    lang_keyboard_up: str
    lang_kitten_name_change_post_dialog: str
    lang_kitten_name_change_pre_dialog: str
    lang_kitten_name_details: str
    lang_kitten_no_name_error: str
    lang_kittens_ask_later: str
    lang_kittens_changed_mind: str
    lang_kittens_never: str
    lang_kittens_no: str
    lang_kittens_yes: str
    lang_language: str
    lang_language_display_name: str
    lang_language_select_confirmation_no: str
    lang_language_select_confirmation_string: str
    lang_language_select_confirmation_title: str
    lang_language_select_confirmation_yes: str
    lang_language_select_title: str
    lang_language_tooltip: str
    lang_lava_water: str
    lang_leader_title: str
    lang_leader_title_eight: str
    lang_leader_title_eight_with_article: str
    lang_leader_title_eight_with_definite_article: str
    lang_leader_title_eight_with_demonstrative_article: str
    lang_leader_title_eight_with_indefinite_article: str
    lang_leader_title_eighteen: str
    lang_leader_title_eighteen_with_article: str
    lang_leader_title_eighteen_with_definite_article: str
    lang_leader_title_eighteen_with_demonstrative_article: str
    lang_leader_title_eighteen_with_indefinite_article: str
    lang_leader_title_eleven: str
    lang_leader_title_eleven_with_article: str
    lang_leader_title_eleven_with_definite_article: str
    lang_leader_title_eleven_with_demonstrative_article: str
    lang_leader_title_eleven_with_indefinite_article: str
    lang_leader_title_fifteen: str
    lang_leader_title_fifteen_with_article: str
    lang_leader_title_fifteen_with_definite_article: str
    lang_leader_title_fifteen_with_demonstrative_article: str
    lang_leader_title_fifteen_with_indefinite_article: str
    lang_leader_title_five: str
    lang_leader_title_five_with_article: str
    lang_leader_title_five_with_definite_article: str
    lang_leader_title_five_with_demonstrative_article: str
    lang_leader_title_five_with_indefinite_article: str
    lang_leader_title_four: str
    lang_leader_title_four_with_article: str
    lang_leader_title_four_with_definite_article: str
    lang_leader_title_four_with_demonstrative_article: str
    lang_leader_title_four_with_indefinite_article: str
    lang_leader_title_fourteen: str
    lang_leader_title_fourteen_with_article: str
    lang_leader_title_fourteen_with_definite_article: str
    lang_leader_title_fourteen_with_demonstrative_article: str
    lang_leader_title_fourteen_with_indefinite_article: str
    lang_leader_title_nine: str
    lang_leader_title_nine_with_article: str
    lang_leader_title_nine_with_definite_article: str
    lang_leader_title_nine_with_demonstrative_article: str
    lang_leader_title_nine_with_indefinite_article: str
    lang_leader_title_nineteen: str
    lang_leader_title_nineteen_with_article: str
    lang_leader_title_nineteen_with_definite_article: str
    lang_leader_title_nineteen_with_demonstrative_article: str
    lang_leader_title_nineteen_with_indefinite_article: str
    lang_leader_title_one: str
    lang_leader_title_one_with_article: str
    lang_leader_title_one_with_definite_article: str
    lang_leader_title_one_with_demonstrative_article: str
    lang_leader_title_one_with_indefinite_article: str
    lang_leader_title_seven: str
    lang_leader_title_seven_with_article: str
    lang_leader_title_seven_with_definite_article: str
    lang_leader_title_seven_with_demonstrative_article: str
    lang_leader_title_seven_with_indefinite_article: str
    lang_leader_title_seventeen: str
    lang_leader_title_seventeen_with_article: str
    lang_leader_title_seventeen_with_definite_article: str
    lang_leader_title_seventeen_with_demonstrative_article: str
    lang_leader_title_seventeen_with_indefinite_article: str
    lang_leader_title_six: str
    lang_leader_title_six_with_article: str
    lang_leader_title_six_with_definite_article: str
    lang_leader_title_six_with_demonstrative_article: str
    lang_leader_title_six_with_indefinite_article: str
    lang_leader_title_sixteen: str
    lang_leader_title_sixteen_with_article: str
    lang_leader_title_sixteen_with_definite_article: str
    lang_leader_title_sixteen_with_demonstrative_article: str
    lang_leader_title_sixteen_with_indefinite_article: str
    lang_leader_title_ten: str
    lang_leader_title_ten_with_article: str
    lang_leader_title_ten_with_definite_article: str
    lang_leader_title_ten_with_demonstrative_article: str
    lang_leader_title_ten_with_indefinite_article: str
    lang_leader_title_thirteen: str
    lang_leader_title_thirteen_with_article: str
    lang_leader_title_thirteen_with_definite_article: str
    lang_leader_title_thirteen_with_demonstrative_article: str
    lang_leader_title_thirteen_with_indefinite_article: str
    lang_leader_title_three: str
    lang_leader_title_three_with_article: str
    lang_leader_title_three_with_definite_article: str
    lang_leader_title_three_with_demonstrative_article: str
    lang_leader_title_three_with_indefinite_article: str
    lang_leader_title_twelve: str
    lang_leader_title_twelve_with_article: str
    lang_leader_title_twelve_with_definite_article: str
    lang_leader_title_twelve_with_demonstrative_article: str
    lang_leader_title_twelve_with_indefinite_article: str
    lang_leader_title_twenty: str
    lang_leader_title_twenty_with_article: str
    lang_leader_title_twenty_with_definite_article: str
    lang_leader_title_twenty_with_demonstrative_article: str
    lang_leader_title_twenty_with_indefinite_article: str
    lang_leader_title_twentyfour: str
    lang_leader_title_twentyfour_with_article: str
    lang_leader_title_twentyfour_with_definite_article: str
    lang_leader_title_twentyfour_with_demonstrative_article: str
    lang_leader_title_twentyfour_with_indefinite_article: str
    lang_leader_title_twentyone: str
    lang_leader_title_twentyone_with_article: str
    lang_leader_title_twentyone_with_definite_article: str
    lang_leader_title_twentyone_with_demonstrative_article: str
    lang_leader_title_twentyone_with_indefinite_article: str
    lang_leader_title_twentythree: str
    lang_leader_title_twentythree_with_article: str
    lang_leader_title_twentythree_with_definite_article: str
    lang_leader_title_twentythree_with_demonstrative_article: str
    lang_leader_title_twentythree_with_indefinite_article: str
    lang_leader_title_twentytwo: str
    lang_leader_title_twentytwo_with_article: str
    lang_leader_title_twentytwo_with_definite_article: str
    lang_leader_title_twentytwo_with_demonstrative_article: str
    lang_leader_title_twentytwo_with_indefinite_article: str
    lang_leader_title_two: str
    lang_leader_title_two_with_article: str
    lang_leader_title_two_with_definite_article: str
    lang_leader_title_two_with_demonstrative_article: str
    lang_leader_title_two_with_indefinite_article: str
    lang_leave_it: str
    lang_leave_shop: str
    lang_leave_task_board: str
    lang_leave_wedding_yes: str
    lang_left_alt: str
    lang_left_eye: str
    lang_legendary: str
    lang_leisurely: str
    lang_lets_chat: str
    lang_light_flashes: str
    lang_light_flashes_tooltip: str
    lang_light_rain: str
    lang_light_snow: str
    lang_liked_items: str
    lang_load_game: str
    lang_load_game_title: str
    lang_lost_items_title: str
    lang_loved_items: str
    lang_lucky_trait_description: str
    lang_lucky_trait_name: str
    lang_magnet_upgrade_tip: str
    lang_mailbox_label: str
    lang_mailbox_no_mail_tip: str
    lang_mailbox_select_tip: str
    lang_mailbox_title: str
    lang_main_game_goto_dialog: str
    lang_main_quest_alert: str
    lang_main_story_complete_congratulations: str
    lang_make_copy: str
    lang_make_copy_title: str
    lang_make_it: str
    lang_map: str
    lang_map_title: str
    lang_master_volume: str
    lang_master_volume_tooltip: str
    lang_max: str
    lang_max_friendship: str
    lang_max_level_reached: str
    lang_maxed_main_game_dialog: str
    lang_maxed_side_game_dialog: str
    lang_meow: str
    lang_meow_effect: str
    lang_mews: str
    lang_mimi: str
    lang_mine_all_warps_unlocked: str
    lang_mine_ascend: str
    lang_mine_ascend_no: str
    lang_mine_ascend_yes: str
    lang_mine_descend_next_level: str
    lang_mine_descend_no: str
    lang_mine_descend_yes: str
    lang_mine_entrance: str
    lang_mine_entrance_blocked: str
    lang_mine_found_key: str
    lang_mine_impressive_stats_flavor: str
    lang_mine_level: str
    lang_mine_level_info: str
    lang_mine_level_info_near_bottom: str
    lang_mine_level_rest_stop: str
    lang_mine_reached_bottom_flavor: str
    lang_mine_repair_no: str
    lang_mine_repair_yes: str
    lang_mine_staircase_flavor_archive: str
    lang_mine_staircase_flavor_broken: str
    lang_mine_staircase_flavor_broken_repairable: str
    lang_mine_staircase_flavor_candles: str
    lang_mine_staircase_flavor_cold: str
    lang_mine_staircase_flavor_combat: str
    lang_mine_staircase_flavor_darkness: str
    lang_mine_staircase_flavor_hot: str
    lang_mine_staircase_flavor_illusion: str
    lang_mine_staircase_flavor_infested: str
    lang_mine_staircase_flavor_jungle: str
    lang_mine_staircase_flavor_lake: str
    lang_mine_staircase_flavor_locked: str
    lang_mine_staircase_flavor_normal: str
    lang_mine_staircase_flavor_ocean: str
    lang_mine_staircase_flavor_poison: str
    lang_mine_staircase_flavor_ruins: str
    lang_mine_staircase_flavor_totem: str
    lang_mine_stairs_unlocked: str
    lang_mine_three_entrance: str
    lang_mine_three_intro_dialog: str
    lang_mine_three_unlocked_dialog: str
    lang_mine_title_first: str
    lang_mine_title_second: str
    lang_mine_title_third: str
    lang_mine_two_entrance: str
    lang_mine_two_intro_dialog: str
    lang_mine_two_unlocked_dialog: str
    lang_miscellaneous: str
    lang_missing_ingredients_tooltip: str
    lang_missing_prerequisite: str
    lang_mod_load_fail_report_text: str
    lang_mod_load_report_text: str
    lang_mod_load_report_title: str
    lang_modify_styles: str
    lang_modify_styles_title: str
    lang_mods: str
    lang_mole_cash: str
    lang_mountain_water: str
    lang_mouse_behavior: str
    lang_mouse_chase_explanation_dialog: str
    lang_mouse_chase_pre_dialog: str
    lang_move: str
    lang_move_down: str
    lang_move_furniture: str
    lang_move_left: str
    lang_move_right: str
    lang_move_up: str
    lang_movement: str
    lang_movement_alt: str
    lang_museum_donate: str
    lang_museum_donate_pre_all_curios_donated_dialog: str
    lang_museum_donate_pre_dialog: str
    lang_museum_donate_pre_no_curios_dialog: str
    lang_music_disc: str
    lang_music_disc_tip: str
    lang_music_volume: str
    lang_music_volume_tooltip: str
    lang_name: str
    lang_name_change: str
    lang_name_change_kitten: str
    lang_name_change_post_dialog: str
    lang_name_change_post_same_dialog: str
    lang_name_change_post_same_kitten_dialog: str
    lang_name_change_pre_dialog: str
    lang_name_change_title: str
    lang_name_unknown: str
    lang_never_mind_doctor: str
    lang_never_mind_doctor_dialog: str
    lang_never_mind_molby: str
    lang_new: str
    lang_new_coat_name_copy: str
    lang_new_coat_name_default: str
    lang_new_coat_title: str
    lang_new_game: str
    lang_new_game_override_question: str
    lang_new_game_plus_label: str
    lang_new_game_plus_title: str
    lang_new_game_title: str
    lang_new_highscore: str
    lang_ngp_file_created_alert: str
    lang_ngp_parent_reject_dialog: str
    lang_ngp_portal: str
    lang_ngp_portal_explanation: str
    lang_ngp_portal_ineligible: str
    lang_ngp_portal_intro: str
    lang_ngp_portal_no_slots_available: str
    lang_ngp_portal_return_to_main_menu_alert: str
    lang_ngp_portal_save_progress_alert: str
    lang_ngp_portal_select_confirm: str
    lang_ngp_portal_unavailable: str
    lang_nice: str
    lang_no: str
    lang_no_available_task_tip: str
    lang_no_cancel: str
    lang_no_changes: str
    lang_no_curios_dialog: str
    lang_no_dont_skip_tutorial: str
    lang_no_jump: str
    lang_no_keep_it: str
    lang_no_known_items: str
    lang_no_meow_effect: str
    lang_no_more_items_to_buy: str
    lang_no_more_items_to_donate: str
    lang_no_more_items_to_sell: str
    lang_no_projects_available: str
    lang_no_projects_constructed: str
    lang_no_save_exists: str
    lang_no_upgrade_skill: str
    lang_no_voice: str
    lang_no_warp_to_town: str
    lang_none: str
    lang_normal: str
    lang_not_applicable: str
    lang_not_enough_inventory_space_curios_dialog: str
    lang_not_now: str
    lang_nothing_lost: str
    lang_npc_social_panel_lvl: str
    lang_off: str
    lang_ok: str
    lang_ok_exclam: str
    lang_on: str
    lang_open_build_menu: str
    lang_open_catalog: str
    lang_open_coat_studio: str
    lang_open_coat_studio_tooltip: str
    lang_option_1: str
    lang_option_2: str
    lang_option_3: str
    lang_option_4: str
    lang_option_5: str
    lang_owned: str
    lang_page: str
    lang_palette: str
    lang_passive_trait: str
    lang_pattern: str
    lang_pause: str
    lang_pause_title: str
    lang_paw_hunt_begin_dialog: str
    lang_paw_hunt_complete: str
    lang_paw_hunt_during_dialog: str
    lang_paw_hunt_pre_dialog: str
    lang_peculiar_water: str
    lang_per_day: str
    lang_percent_chance: str
    lang_perfect: str
    lang_perk_active: str
    lang_perk_active_question: str
    lang_perk_inactive: str
    lang_persistent_trait_description: str
    lang_persistent_trait_name: str
    lang_pick_a_turtle_title: str
    lang_pixel_perfect: str
    lang_place: str
    lang_place_furniture: str
    lang_platform: str
    lang_play_festival_game: str
    lang_player_random_name_eight: str
    lang_player_random_name_eighteen: str
    lang_player_random_name_eleven: str
    lang_player_random_name_fifteen: str
    lang_player_random_name_five: str
    lang_player_random_name_four: str
    lang_player_random_name_fourteen: str
    lang_player_random_name_fourty: str
    lang_player_random_name_nine: str
    lang_player_random_name_nineteen: str
    lang_player_random_name_one: str
    lang_player_random_name_seven: str
    lang_player_random_name_seventeen: str
    lang_player_random_name_six: str
    lang_player_random_name_sixteen: str
    lang_player_random_name_ten: str
    lang_player_random_name_thirteen: str
    lang_player_random_name_thirty: str
    lang_player_random_name_thirtyeight: str
    lang_player_random_name_thirtyfive: str
    lang_player_random_name_thirtyfour: str
    lang_player_random_name_thirtynine: str
    lang_player_random_name_thirtyone: str
    lang_player_random_name_thirtyseven: str
    lang_player_random_name_thirtysix: str
    lang_player_random_name_thirtythree: str
    lang_player_random_name_thirtytwo: str
    lang_player_random_name_three: str
    lang_player_random_name_twelve: str
    lang_player_random_name_twenty: str
    lang_player_random_name_twentyeight: str
    lang_player_random_name_twentyfive: str
    lang_player_random_name_twentyfour: str
    lang_player_random_name_twentynine: str
    lang_player_random_name_twentyone: str
    lang_player_random_name_twentyseven: str
    lang_player_random_name_twentysix: str
    lang_player_random_name_twentythree: str
    lang_player_random_name_twentytwo: str
    lang_player_random_name_two: str
    lang_pm: str
    lang_pond_news_autumn_first: str
    lang_pond_news_autumn_last: str
    lang_pond_news_autumn_middle: str
    lang_pond_news_end: str
    lang_pond_news_festival_today: str
    lang_pond_news_festival_tomorrow: str
    lang_pond_news_good_afternoon: str
    lang_pond_news_good_evening: str
    lang_pond_news_good_morning: str
    lang_pond_news_no_news: str
    lang_pond_news_npc_birthday: str
    lang_pond_news_npc_birthday_coco: str
    lang_pond_news_player_birthday: str
    lang_pond_news_spring_first: str
    lang_pond_news_spring_last: str
    lang_pond_news_spring_middle: str
    lang_pond_news_start: str
    lang_pond_news_summer_first: str
    lang_pond_news_summer_last: str
    lang_pond_news_summer_middle: str
    lang_pond_news_winter_first: str
    lang_pond_news_winter_last: str
    lang_pond_news_winter_middle: str
    lang_pond_visions_dk_e1: str
    lang_pond_visions_dk_e2: str
    lang_pond_visions_dk_e3: str
    lang_pond_visions_dk_e4: str
    lang_pond_visions_dk_e5: str
    lang_pond_visions_dk_e6: str
    lang_pond_visions_dk_e7: str
    lang_pond_visions_dk_e8: str
    lang_pond_visions_fof_e1: str
    lang_pond_visions_fof_e2: str
    lang_pond_visions_fof_e3: str
    lang_pond_visions_fof_e4: str
    lang_pond_visions_gd_e1: str
    lang_pond_visions_gd_e2: str
    lang_pond_visions_gd_e3: str
    lang_pond_visions_gd_e4: str
    lang_pond_visions_gp_e1: str
    lang_pond_visions_gp_e2: str
    lang_pond_visions_gp_e3: str
    lang_pond_visions_gp_e4: str
    lang_pond_visions_jm_e1: str
    lang_pond_visions_jm_e2: str
    lang_pond_visions_jm_e3: str
    lang_pond_visions_jm_e4: str
    lang_pond_visions_jm_e5: str
    lang_pond_visions_jm_e6: str
    lang_pond_visions_jm_e7: str
    lang_pond_visions_jm_e8: str
    lang_pond_visions_no_programming_today: str
    lang_pond_visions_tgwd_s1e1: str
    lang_pond_visions_tgwd_s1e2: str
    lang_pond_visions_tgwd_s1e3: str
    lang_pond_visions_tgwd_s1e4: str
    lang_pond_visions_tgwd_s1e5: str
    lang_pond_visions_tgwd_s1e6: str
    lang_pond_visions_tgwd_s1e7: str
    lang_pond_visions_tgwd_s1e8: str
    lang_pond_visions_tt_e1: str
    lang_pond_visions_tt_e2: str
    lang_pond_visions_tt_e3: str
    lang_pond_visions_tt_e4: str
    lang_pond_weather: str
    lang_pond_weather_blizzard: str
    lang_pond_weather_fog: str
    lang_pond_weather_fog_and_rain: str
    lang_pond_weather_fog_and_snow: str
    lang_pond_weather_heavy_rain: str
    lang_pond_weather_heavy_snow: str
    lang_pond_weather_light_rain: str
    lang_pond_weather_light_snow: str
    lang_pond_weather_pattern_afternoon_blizzard: str
    lang_pond_weather_pattern_afternoon_thunderstorm: str
    lang_pond_weather_pattern_blizzard_morning: str
    lang_pond_weather_pattern_foggy_day: str
    lang_pond_weather_pattern_foggy_morning: str
    lang_pond_weather_pattern_foggy_morning_rainy_day: str
    lang_pond_weather_pattern_foggy_morning_snowy_day: str
    lang_pond_weather_pattern_foggy_night: str
    lang_pond_weather_pattern_nasty_day: str
    lang_pond_weather_pattern_nasty_day_snow: str
    lang_pond_weather_pattern_night_drizzle: str
    lang_pond_weather_pattern_night_flurries: str
    lang_pond_weather_pattern_rainy_day: str
    lang_pond_weather_pattern_rainy_evening: str
    lang_pond_weather_pattern_rainy_morning: str
    lang_pond_weather_pattern_severe_blizzard: str
    lang_pond_weather_pattern_severe_storm: str
    lang_pond_weather_pattern_snowy_day: str
    lang_pond_weather_pattern_snowy_evening: str
    lang_pond_weather_pattern_snowy_morning: str
    lang_pond_weather_pattern_stormy_morning: str
    lang_pond_weather_pattern_sunny_day: str
    lang_pond_weather_rain: str
    lang_pond_weather_snow: str
    lang_pond_weather_sunny: str
    lang_pond_weather_thunderstorm: str
    lang_pond_weather_tomorrow: str
    lang_pond_wisdom_0: str
    lang_pond_wisdom_1: str
    lang_pond_wisdom_10: str
    lang_pond_wisdom_11: str
    lang_pond_wisdom_12: str
    lang_pond_wisdom_13: str
    lang_pond_wisdom_14: str
    lang_pond_wisdom_15: str
    lang_pond_wisdom_16: str
    lang_pond_wisdom_17: str
    lang_pond_wisdom_18: str
    lang_pond_wisdom_19: str
    lang_pond_wisdom_2: str
    lang_pond_wisdom_20: str
    lang_pond_wisdom_21: str
    lang_pond_wisdom_22: str
    lang_pond_wisdom_23: str
    lang_pond_wisdom_24: str
    lang_pond_wisdom_25: str
    lang_pond_wisdom_26: str
    lang_pond_wisdom_27: str
    lang_pond_wisdom_28: str
    lang_pond_wisdom_29: str
    lang_pond_wisdom_3: str
    lang_pond_wisdom_30: str
    lang_pond_wisdom_31: str
    lang_pond_wisdom_32: str
    lang_pond_wisdom_33: str
    lang_pond_wisdom_34: str
    lang_pond_wisdom_35: str
    lang_pond_wisdom_36: str
    lang_pond_wisdom_37: str
    lang_pond_wisdom_38: str
    lang_pond_wisdom_39: str
    lang_pond_wisdom_4: str
    lang_pond_wisdom_5: str
    lang_pond_wisdom_6: str
    lang_pond_wisdom_7: str
    lang_pond_wisdom_8: str
    lang_pond_wisdom_9: str
    lang_pond_wisdom_end: str
    lang_pond_wisdom_start: str
    lang_post_dark_ruins_narrative: str
    lang_post_dream_sequence_dialog: str
    lang_post_heal_buddy_dialog: str
    lang_pounce_auto_success: str
    lang_power_paw: str
    lang_power_paw_charge: str
    lang_power_paw_health: str
    lang_power_paw_hunger: str
    lang_power_paw_intro: str
    lang_power_paw_luck: str
    lang_power_paw_social_grace: str
    lang_power_paw_speed: str
    lang_press: str
    lang_press_demo: str
    lang_prey: str
    lang_prey_perk_activated_notice: str
    lang_prey_radius: str
    lang_prey_stockpile: str
    lang_prey_stockpile_description: str
    lang_prey_stockpile_perk_description: str
    lang_price: str
    lang_project_constructed: str
    lang_promo_code: str
    lang_promo_code_already_unlocked: str
    lang_promo_code_invalid: str
    lang_promo_code_title: str
    lang_promo_code_unlocked: str
    lang_pumpkin_roll_explanation_dialog: str
    lang_pumpkin_roll_pre_dialog: str
    lang_purchase_item: str
    lang_quarry_dirt_path: str
    lang_quick: str
    lang_quick_time: str
    lang_rain: str
    lang_random_enemies: str
    lang_random_enemies_tooltip: str
    lang_randomize: str
    lang_rare: str
    lang_ready_to_level_up: str
    lang_ready_to_level_up_short: str
    lang_rebind_controls: str
    lang_rebind_controls_title: str
    lang_rebind_controls_tooltip: str
    lang_rebind_key: str
    lang_rebind_key_title: str
    lang_recipe: str
    lang_recipe_tip: str
    lang_record_player_title: str
    lang_recruit_more_cats: str
    lang_recruit_place_buildings: str
    lang_recruit_place_garden: str
    lang_recruit_place_seedmaker: str
    lang_recruit_post_dialog_1: str
    lang_recruit_post_dialog_2: str
    lang_recruit_post_dialog_3: str
    lang_recruit_post_dialog_4: str
    lang_recruit_post_dialog_5: str
    lang_recruited: str
    lang_recruited_dialog: str
    lang_recruited_gardening_unlocked: str
    lang_recruited_museum_unlocked: str
    lang_recruited_squads_unlocked: str
    lang_recruited_wrap_up_dialog: str
    lang_red_initial: str
    lang_refined_litter: str
    lang_refined_litter_tooltip: str
    lang_region_uid: str
    lang_relaxed: str
    lang_release: str
    lang_remove: str
    lang_remove_floor: str
    lang_renowned_trait_description: str
    lang_renowned_trait_name: str
    lang_reset: str
    lang_reset_cooldowns: str
    lang_reset_steam_achievements: str
    lang_resume: str
    lang_retrain: str
    lang_retrain_title: str
    lang_retrieve: str
    lang_retrieve_all: str
    lang_rgb: str
    lang_right_alt: str
    lang_right_eye: str
    lang_rigid: str
    lang_rival_marriage_affirm: str
    lang_rival_marriage_affirm_2: str
    lang_rival_marriage_affirm_3: str
    lang_rival_marriage_ask_1: str
    lang_rival_marriage_ask_2: str
    lang_rival_marriage_ask_affirm_confirm: str
    lang_rival_marriage_ask_affirm_confirm_part2: str
    lang_rival_marriage_ask_affirm_confirm_post: str
    lang_rival_marriage_ask_affirm_confirm_post_part2: str
    lang_rival_marriage_ask_deny_confirm: str
    lang_rival_marriage_ask_deny_confirm_part2: str
    lang_rival_marriage_ask_deny_confirm_post: str
    lang_rival_marriage_ask_deny_confirm_post_part2: str
    lang_rival_marriage_attend: str
    lang_rival_marriage_cannot_attend: str
    lang_rival_marriage_deny: str
    lang_rival_marriage_deny_2: str
    lang_rival_marriage_deny_3: str
    lang_rival_marriage_kittens_announcement_1: str
    lang_rival_marriage_kittens_announcement_2: str
    lang_rival_marriage_kittens_announcement_3: str
    lang_rival_marriage_kittens_announcement_4: str
    lang_rival_marriage_kittens_announcement_5: str
    lang_rival_marriage_kittens_announcement_6: str
    lang_rival_marriage_pending_1: str
    lang_rival_marriage_pending_2: str
    lang_rival_marriage_pending_3: str
    lang_rival_marriage_pending_4: str
    lang_rival_marriage_pending_5: str
    lang_rival_marriage_pending_attend: str
    lang_rival_marriage_pending_cannot_attend: str
    lang_rock_floor_1: str
    lang_rock_floor_2: str
    lang_rotate: str
    lang_ruins_floor: str
    lang_ruins_path: str
    lang_ruins_wall: str
    lang_rumble: str
    lang_rumble_tooltip: str
    lang_rumble_tooltip_switch: str
    lang_run: str
    lang_sand: str
    lang_sand_floor: str
    lang_sand_path: str
    lang_sand_stockpile: str
    lang_sand_stockpile_description: str
    lang_saturation_initial: str
    lang_save_coat: str
    lang_save_coat_title: str
    lang_save_progress: str
    lang_save_progress_pause_confirm: str
    lang_save_progress_pause_dialog_question: str
    lang_save_progress_pause_dialog_question_in_den: str
    lang_save_progress_pause_failed: str
    lang_save_progress_pause_no: str
    lang_save_progress_pause_yes: str
    lang_scroll_faster: str
    lang_season: str
    lang_select: str
    lang_select_task_tip: str
    lang_sell: str
    lang_sell_all: str
    lang_sell_everything: str
    lang_sell_everything_item: str
    lang_sell_how_many: str
    lang_sell_item: str
    lang_sell_items: str
    lang_sell_items_title: str
    lang_sell_quantity: str
    lang_settings: str
    lang_settle_here: str
    lang_settle_where_title: str
    lang_shallow_water: str
    lang_shop: str
    lang_shop_title: str
    lang_show_tips: str
    lang_show_tips_tooltip: str
    lang_simple: str
    lang_skill_1: str
    lang_skill_2: str
    lang_skill_3: str
    lang_skill_4: str
    lang_skill_description_botany: str
    lang_skill_description_deep_cuts: str
    lang_skill_description_diplomacy: str
    lang_skill_description_hunters_gamble: str
    lang_skill_description_kindly_purr: str
    lang_skill_description_lions_roar: str
    lang_skill_description_menacing_fangs: str
    lang_skill_description_mortal_wound: str
    lang_skill_description_nine_lives: str
    lang_skill_description_pinecone_toss: str
    lang_skill_description_rejuvenate: str
    lang_skill_description_return_home: str
    lang_skill_description_shield: str
    lang_skill_description_spectral_dodge: str
    lang_skill_description_summon_allies: str
    lang_skill_description_sweet_melody: str
    lang_skill_description_tenacity: str
    lang_skill_description_tigers_breath: str
    lang_skill_description_warding_scrawl: str
    lang_skill_description_wild_slash: str
    lang_skill_interrupted: str
    lang_skill_just_unlocked_dialog: str
    lang_skill_locked: str
    lang_skill_max_rank: str
    lang_skill_name_botany: str
    lang_skill_name_deep_cuts: str
    lang_skill_name_diplomacy: str
    lang_skill_name_hunters_gamble: str
    lang_skill_name_kindly_purr: str
    lang_skill_name_lions_roar: str
    lang_skill_name_menacing_fangs: str
    lang_skill_name_mortal_wound: str
    lang_skill_name_nine_lives: str
    lang_skill_name_pinecone_toss: str
    lang_skill_name_rejuvenate: str
    lang_skill_name_return_home: str
    lang_skill_name_shield: str
    lang_skill_name_spectral_dodge: str
    lang_skill_name_summon_allies: str
    lang_skill_name_sweet_melody: str
    lang_skill_name_tenacity: str
    lang_skill_name_tigers_breath: str
    lang_skill_name_warding_scrawl: str
    lang_skill_name_wild_slash: str
    lang_skill_rank: str
    lang_skill_rank_1: str
    lang_skill_rank_10: str
    lang_skill_rank_2: str
    lang_skill_rank_3: str
    lang_skill_rank_4: str
    lang_skill_rank_5: str
    lang_skill_rank_6: str
    lang_skill_rank_7: str
    lang_skill_rank_8: str
    lang_skill_rank_9: str
    lang_skill_unlock: str
    lang_skill_warping: str
    lang_skill_yes_equip_it: str
    lang_skills: str
    lang_skills_title: str
    lang_skip: str
    lang_skip_event: str
    lang_skip_tutorial_dialog: str
    lang_slot_no_data: str
    lang_slot_skill_tip: str
    lang_smooth: str
    lang_sneak: str
    lang_snore_zzz: str
    lang_snow: str
    lang_snowball_fight_explanation_dialog: str
    lang_snowball_fight_pre_dialog: str
    lang_so_close: str
    lang_social: str
    lang_social_title: str
    lang_social_tooltip: str
    lang_sound_effects_volume: str
    lang_sound_effects_volume_tooltip: str
    lang_speedy: str
    lang_spirit_ask_kittens: str
    lang_spirit_introduce_kittens: str
    lang_spirit_kittens_confirm_never: str
    lang_spirit_kittens_later: str
    lang_spirit_kittens_no: str
    lang_spirit_kittens_yes: str
    lang_spirit_post_kittens: str
    lang_spouse_ask_kittens: str
    lang_spouse_introduce_kittens: str
    lang_spouse_kittens_confirm_never: str
    lang_spouse_kittens_later: str
    lang_spouse_kittens_no: str
    lang_spouse_kittens_yes: str
    lang_spouse_post_kittens: str
    lang_spring: str
    lang_spring1record: str
    lang_spring2record: str
    lang_spring3record: str
    lang_spring_1: str
    lang_spring_10: str
    lang_spring_2: str
    lang_spring_3: str
    lang_spring_4: str
    lang_spring_5: str
    lang_spring_6: str
    lang_spring_7: str
    lang_spring_8: str
    lang_spring_9: str
    lang_spring_carving: str
    lang_springfestivalrecord: str
    lang_squad_already_there: str
    lang_squad_attack_alert: str
    lang_squad_cannot_assign_daily_battle: str
    lang_squad_defend_alert: str
    lang_squads_available: str
    lang_stats: str
    lang_statue_plaque: str
    lang_statue_pre_dialog: str
    lang_stockpile_bonus: str
    lang_stockpile_help_dialog: str
    lang_stockpile_help_no_talon_dialog: str
    lang_stockpile_help_talon_dialog: str
    lang_stockpiles: str
    lang_stockpiles_pre_dialog: str
    lang_stone: str
    lang_stone_stockpile: str
    lang_stone_stockpile_description: str
    lang_stone_wall: str
    lang_storage_label: str
    lang_storage_title: str
    lang_store: str
    lang_store_all: str
    lang_strong: str
    lang_sturdy_chisels: str
    lang_sturdy_chisels_tooltip: str
    lang_style_i: str
    lang_style_ii: str
    lang_style_iii: str
    lang_style_iv: str
    lang_style_v: str
    lang_style_vi: str
    lang_subtle_trait_description: str
    lang_subtle_trait_name: str
    lang_summer: str
    lang_summer1record: str
    lang_summer2record: str
    lang_summer3record: str
    lang_summer_1: str
    lang_summer_10: str
    lang_summer_2: str
    lang_summer_3: str
    lang_summer_4: str
    lang_summer_5: str
    lang_summer_6: str
    lang_summer_7: str
    lang_summer_8: str
    lang_summer_9: str
    lang_summer_carving: str
    lang_summerfestivalrecord: str
    lang_summon_molby: str
    lang_sunny: str
    lang_swamp_water: str
    lang_tail: str
    lang_talisman_no: str
    lang_talisman_use_prompt_dialog: str
    lang_talisman_yes: str
    lang_tank: str
    lang_task_accept: str
    lang_task_accept_failed: str
    lang_task_board_dialog: str
    lang_task_board_title: str
    lang_task_board_tutorial: str
    lang_task_board_tutorial_dialog: str
    lang_task_bring_to: str
    lang_task_canceled_dialog: str
    lang_task_collect_items: str
    lang_task_completed: str
    lang_task_daily_battles: str
    lang_task_darkcandles: str
    lang_task_description_confrontation: str
    lang_task_description_darkportents: str
    lang_task_description_intowildwood: str
    lang_task_description_reclamation: str
    lang_task_description_wildwoodrestored: str
    lang_task_gardening: str
    lang_task_herbs: str
    lang_task_log: str
    lang_task_log_title: str
    lang_task_mine_descend: str
    lang_task_objective_complete_intro: str
    lang_task_objective_explore_the_wildwood: str
    lang_task_objective_find_dark_ruins: str
    lang_task_objective_purify_temple: str
    lang_task_objective_visit_temple: str
    lang_task_out_of_season_tip: str
    lang_task_prey: str
    lang_task_ready_to_turn_in: str
    lang_task_ready_to_turn_in_tip: str
    lang_task_reward: str
    lang_task_scouting: str
    lang_task_seasonal_carvings: str
    lang_task_talk_to: str
    lang_task_title_confrontation: str
    lang_task_title_darkportents: str
    lang_task_title_intowildwood: str
    lang_task_title_reclamation: str
    lang_task_title_wildwoodrestored: str
    lang_task_tokens: str
    lang_task_turn_in_items_confirmation: str
    lang_task_voidlings: str
    lang_taskboard_not_enough_currency: str
    lang_taskboard_not_enough_inventory: str
    lang_taskboard_shop_buy: str
    lang_taskboard_shop_name_title: str
    lang_taskboard_shop_thanks: str
    lang_throw_snowball: str
    lang_thunderstorm: str
    lang_tile: str
    lang_time_modifier: str
    lang_time_passage: str
    lang_time_passage_tooltip: str
    lang_too_bad: str
    lang_too_many_items_dialog: str
    lang_too_many_world_objects_dialog: str
    lang_too_much_furniture_dialog: str
    lang_tooltip_added_to_collections: str
    lang_tooltip_inventory_full: str
    lang_tooltip_too_close: str
    lang_tooltip_try_getting_closer: str
    lang_tooltip_water_missed: str
    lang_torso: str
    lang_tough_trait_description: str
    lang_tough_trait_name: str
    lang_traits_cannot_afford: str
    lang_traits_changed_success: str
    lang_translation_fallback: str
    lang_translation_fallback_tooltip: str
    lang_treasure: str
    lang_treasure_perk_activated_notice: str
    lang_treasure_stockpile: str
    lang_treasure_stockpile_description: str
    lang_treasure_stockpile_perk_description: str
    lang_true: str
    lang_tunnel_blocked_dialog: str
    lang_turtle_race_explanation_dialog: str
    lang_turtle_race_opponents_dialog: str
    lang_turtle_race_pre_dialog: str
    lang_tutorial_attack_prompt: str
    lang_tutorial_charged_attack_prompt: str
    lang_tutorial_dialog_eat_item: str
    lang_tutorial_dialog_hold_item: str
    lang_tutorial_dodge_prompt: str
    lang_tutorial_dont_go_east_yet_dialog: str
    lang_tutorial_dont_go_west_yet2_dialog: str
    lang_tutorial_dont_go_west_yet_dialog: str
    lang_tutorial_dont_leave_camp_dialog: str
    lang_tutorial_flick: str
    lang_tutorial_give_spark_valerian: str
    lang_tutorial_hint0: str
    lang_tutorial_hint1: str
    lang_tutorial_hint10: str
    lang_tutorial_hint11: str
    lang_tutorial_hint12: str
    lang_tutorial_hint13: str
    lang_tutorial_hint14: str
    lang_tutorial_hint15: str
    lang_tutorial_hint16: str
    lang_tutorial_hint17: str
    lang_tutorial_hint18: str
    lang_tutorial_hint19: str
    lang_tutorial_hint2: str
    lang_tutorial_hint20: str
    lang_tutorial_hint3: str
    lang_tutorial_hint4: str
    lang_tutorial_hint5: str
    lang_tutorial_hint6: str
    lang_tutorial_hint7: str
    lang_tutorial_hint8: str
    lang_tutorial_hint9: str
    lang_tutorial_hunger_prompt: str
    lang_tutorial_hunger_prompt2: str
    lang_tutorial_hunt_prompt: str
    lang_tutorial_inventory_open_prompt: str
    lang_tutorial_skills_prompt: str
    lang_uncommon: str
    lang_undergroundindustryrecord: str
    lang_unidentified_curios_have: str
    lang_unlock_skill_dialog: str
    lang_unlocks: str
    lang_unsaved_progress: str
    lang_up_alt: str
    lang_update_floorplan_title: str
    lang_upgrade: str
    lang_upgrade_skill_dialog: str
    lang_uproot_dialog: str
    lang_uproot_it: str
    lang_utility: str
    lang_v_sync: str
    lang_v_sync_tooltip: str
    lang_value_initial: str
    lang_very_easy: str
    lang_very_hard: str
    lang_video_options: str
    lang_video_options_title: str
    lang_video_options_tooltip: str
    lang_view: str
    lang_view_buddy_stats: str
    lang_view_collections: str
    lang_view_collections_tooltip: str
    lang_view_colony_stockpiles: str
    lang_view_daily_task: str
    lang_view_storage: str
    lang_view_task_log: str
    lang_view_task_log_tooltip: str
    lang_visit_shop: str
    lang_visit_task_board_shop: str
    lang_vivacious_trait_description: str
    lang_vivacious_trait_name: str
    lang_voice: str
    lang_voice_pitch: str
    lang_wall_attachment: str
    lang_warp_constructed_dialog: str
    lang_warp_entrance_northeast_dialog_prompt: str
    lang_warp_entrance_northwest_dialog_prompt: str
    lang_warp_entrance_southeast_dialog_prompt: str
    lang_warp_entrance_southwest_dialog_prompt: str
    lang_warp_northeast: str
    lang_warp_northeast_tooltip: str
    lang_warp_northwest: str
    lang_warp_northwest_tooltip: str
    lang_warp_southeast: str
    lang_warp_southeast_tooltip: str
    lang_warp_southwest: str
    lang_warp_southwest_tooltip: str
    lang_warp_to_town_dialog_prompt: str
    lang_wc_choice_spare: str
    lang_wc_choice_vanquish: str
    lang_wc_complete_alert: str
    lang_wc_dr1_dialog_0: str
    lang_wc_dr1_dialog_1: str
    lang_wc_dr2_dialog_0: str
    lang_wc_dr2_dialog_1: str
    lang_wc_dr3_dialog_0: str
    lang_wc_dr3_dialog_1: str
    lang_wc_dr4_dialog_0: str
    lang_wc_dr4_dialog_1: str
    lang_wc_dr5_dialog_0: str
    lang_wc_dr5_dialog_1: str
    lang_wc_dr5_dialog_2: str
    lang_wc_dr5_dialog_3: str
    lang_wc_dr5_dialog_4: str
    lang_wc_dr5_dialog_5: str
    lang_wc_dr5_dialog_6: str
    lang_wc_dr5_dialog_7: str
    lang_wc_dr5_dialog_8: str
    lang_wc_dr5_dialog_9: str
    lang_wc_dr5_dialog_spared: str
    lang_wc_dr5_dialog_vanquished: str
    lang_wc_joined_alert: str
    lang_wc_spared_dialog_0: str
    lang_wc_spared_dialog_1: str
    lang_wc_spared_dialog_2: str
    lang_wc_spared_dialog_3: str
    lang_wc_spared_dialog_4: str
    lang_wc_spared_dialog_5: str
    lang_wc_vanquished_dialog_0: str
    lang_wc_vanquished_dialog_1: str
    lang_wc_vanquished_dialog_2: str
    lang_wc_vanquished_dialog_3: str
    lang_wc_vanquished_dialog_4: str
    lang_wc_voidlings_alert: str
    lang_weak: str
    lang_wear_it: str
    lang_weather: str
    lang_wedding_leave_prompt: str
    lang_wedding_officiant_dialog_begin: str
    lang_wedding_officiant_dialog_cheers: str
    lang_wedding_officiant_dialog_post_vows: str
    lang_wedding_officiant_dialog_spouse_vow_question: str
    lang_wedding_venues_title: str
    lang_welcome_to_the_demo_title: str
    lang_where_to_send_squads: str
    lang_white_stones_path: str
    lang_wildwoodrecord: str
    lang_winter: str
    lang_winter1record: str
    lang_winter2record: str
    lang_winter3record: str
    lang_winter_1: str
    lang_winter_10: str
    lang_winter_2: str
    lang_winter_3: str
    lang_winter_4: str
    lang_winter_5: str
    lang_winter_6: str
    lang_winter_7: str
    lang_winter_8: str
    lang_winter_9: str
    lang_winter_carving: str
    lang_winterfestivalrecord: str
    lang_wood: str
    lang_wood_floor: str
    lang_wood_horizontal_path: str
    lang_wood_stockpile: str
    lang_wood_stockpile_description: str
    lang_wood_vertical_path: str
    lang_wood_wall: str
    lang_xp: str
    lang_year: str
    lang_yes: str
    lang_yes_apply_them: str
    lang_yes_cancel: str
    lang_yes_complete_task: str
    lang_yes_delete_it: str
    lang_yes_discard_them: str
    lang_yes_dismiss: str
    lang_yes_donate_curio: str
    lang_yes_exit: str
    lang_yes_level_up: str
    lang_yes_please: str
    lang_yes_save_it: str
    lang_yes_skip_tutorial: str
    lang_yes_unlock_skill: str
    lang_yes_upgrade_skill: str
    lang_yes_warp_to_town: str
    lang_your_new_kitten_title: str
