"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://cattails-game.fandom.com/wiki/Cattails_Game_Wiki
  name = cattailsauto

Please do not commit this to the Git repository!
"""
from pywikibot import family


class Family(family.Family):  # noqa: D101

    name = 'cattailsauto'
    langs = {
        'en': 'cattails-game.fandom.com',
    }

    def scriptpath(self, code):
        return {
            'en': '',
        }[code]

    def protocol(self, code):
        return {
            'en': 'https',
        }[code]
